services:
    - service: activemq
      port: 61616

    - service: redis
      port: 6379

    - service: riak
      port: 8087

    - service: mysql
      port: 3306
    
    - service: voyager-index
      port: 4242
      host: devsolaris

    - service: voyager-query
      port: 4246
      host: devsolaris
